#!/bin/sh

if [ $# -lt 3 ] ; then
    echo "$0 <old pattern> <new pattern> <files...>"
    echo "Replace <old patter> with <new pattern> in all <files>"
    exit 1
fi

old=$1
shift 1
new=$1
shift 1

for f in $@ ; do  
    sed -e "s/${old}/${new}/g" $f > tmpfileblah 
    mv tmpfileblah $f
done


exit 0
